# Generated by Django 4.1.7 on 2023-07-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('1', 'Achham'), ('2', 'Arghakhanchi'), ('3', 'Baglung'), ('4', 'Baitadi'), ('5', 'Bajhang'), ('6', 'Bajura'), ('7', 'Banke'), ('8', 'Bara'), ('9', 'Bardiya'), ('10', 'Bhaktapur'), ('11', 'Bhojpur'), ('12', 'Chitwan'), ('13', 'Dadeldhura'), ('14', 'Dailekh'), ('15', 'Dang'), ('16', 'Darchula'), ('17', 'Dhading'), ('18', 'Dhankuta'), ('19', 'Dhanusa'), ('20', 'Dolakha'), ('21', 'Dolpa'), ('22', 'Doti'), ('23', 'Eastern Rukum'), ('24', 'Gorkha'), ('25', 'Gulmi'), ('26', 'Humla'), ('27', 'Ilam'), ('28', 'Jajarkot'), ('29', 'Jhapa'), ('30', 'Jumla'), ('31', 'Kailali'), ('32', 'Kalikot'), ('33', 'Kanchanpur'), ('34', 'Kapilvastu'), ('35', 'Kaski'), ('36', 'Kathmandu'), ('37', 'Kavrepalanchok'), ('38', 'Khotang'), ('39', 'Lalitpur'), ('40', 'Lamjung'), ('41', 'Mahottari'), ('42', 'Makwanpur'), ('43', 'Manang'), ('44', 'Morang'), ('45', 'Mugu'), ('46', 'Mustang'), ('47', 'Myagdi'), ('48', 'Nawalpur'), ('49', 'Nuwakot'), ('50', 'Okhaldhunga'), ('51', 'Palpa'), ('52', 'Panchthar'), ('53', 'Parbat'), ('54', 'Parsa'), ('55', 'Pyuthan'), ('56', 'Ramechhap'), ('57', 'Rasuwa'), ('58', 'Rautahat'), ('59', 'Rolpa'), ('60', 'Rukum West'), ('61', 'Rupandehi'), ('62', 'Salyan'), ('63', 'Sankhuwasabha'), ('64', 'Saptari'), ('65', 'Sarlahi'), ('66', 'Sindhuli'), ('67', 'Sindhupalchok'), ('68', 'Siraha'), ('69', 'Solukhumbu'), ('70', 'Sunsari'), ('71', 'Surkhet'), ('72', 'Syangja'), ('73', 'Tanahun'), ('74', 'Taplejung'), ('75', 'Terhathum'), ('76', 'Udayapur'), ('77', 'Western Rukum')], max_length=3, verbose_name='District')),
                ('municipality', models.CharField(max_length=255, verbose_name='Municipality')),
                ('wardno', models.PositiveIntegerField(null=True, verbose_name='Ward No.')),
                ('areainsqm', models.CharField(max_length=10, verbose_name='Area in Square Meter')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelno', models.CharField(max_length=30, verbose_name='Model No.')),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Category')),
                ('types', models.CharField(choices=[('1', 'Multi-Rotor'), ('2', 'Fixed-Wing'), ('3', 'Single-Rotor'), ('4', 'Fixed-Wing Hybrid VTOL')], max_length=10, verbose_name='Type')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Weight')),
                ('max_takeoff', models.CharField(max_length=30, verbose_name='Maximum TakeOff')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('tele_no', models.CharField(max_length=10, unique=True, verbose_name='Phone No.')),
                ('pilot_fname', models.CharField(max_length=30, verbose_name='Pilot First Name')),
                ('pilot_lname', models.CharField(max_length=30, verbose_name='Pilot Last Name')),
                ('pilot_email', models.EmailField(max_length=254, verbose_name='Pilot Email')),
                ('pilot_tele_no', models.CharField(max_length=10, verbose_name='Pilot Phone No.')),
            ],
        ),
        migrations.CreateModel(
            name='DronePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('purpose', models.CharField(max_length=255, verbose_name='Purpose of Flight')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.area')),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.drone')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.owner')),
            ],
        ),
    ]
