# Generated by Django 4.1.7 on 2023-07-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_drone_reg_id_alter_dronepermit_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='owners',
            field=models.ForeignKey(db_column='owners_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='Main.owner'),
        ),
        migrations.AlterField(
            model_name='dronepermit',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='Main.drone'),
        ),
        migrations.AlterField(
            model_name='dronepermit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_permits', to='Main.owner'),
        ),
    ]
